### ISSUE TITLE
BridgeBuilder v1.0.6地图边缘搭桥导致崩溃

### ISSUE THREAD

**Issue by 35117** [Controllerdestiny/TShockPlugin#76]
服务器内玩家在地图边缘准备搭桥打猪
在左边海洋处向左边搭桥时，服务器崩溃
报错显示

2024-05-03 14:46:48 - TShock: INFO: 枫叶执行了/bridge。
2024-05-03 14:46:48 - TShock: ERROR: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ModFramework.DefaultCollection`1.get_Item(Int32 x, Int32 y)
   at BridgeBuilder.BridgeBuilder.CheckTileAvailability(Int32 x, Int32 y, TSPlayer plr, Int32 directionX, Int32 directionY)
   at BridgeBuilder.BridgeBuilder.<>c__DisplayClass13_0.<BridgeCmd>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at BridgeBuilder.BridgeBuilder.BridgeCmd(CommandArgs args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by ACaiCat** [comment]
估计是没有判断地图边缘爆了

**Comment by ACaiCat** [comment]
#77 已解决
